"""Initial migration

Revision ID: e5976a9f4fef
Revises: 
Create Date: 2025-11-07 23:55:12.325042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5976a9f4fef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brukere',
    sa.Column('bruker_id', sa.Integer(), nullable=False),
    sa.Column('brukernavn', sa.String(length=50), nullable=False),
    sa.Column('passord_hash', sa.String(length=255), nullable=False),
    sa.Column('epost', sa.String(length=255), nullable=False),
    sa.Column('opprettet_dato', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=True),
    sa.Column('rolle', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('bruker_id')
    )
    op.create_index(op.f('ix_brukere_bruker_id'), 'brukere', ['bruker_id'], unique=False)
    op.create_index(op.f('ix_brukere_brukernavn'), 'brukere', ['brukernavn'], unique=True)
    op.create_index(op.f('ix_brukere_epost'), 'brukere', ['epost'], unique=True)
    op.create_table('muskler',
    sa.Column('muskel_id', sa.Integer(), nullable=False),
    sa.Column('muskel_navn', sa.String(length=100), nullable=False),
    sa.Column('hovedkategori', sa.String(length=50), nullable=False),
    sa.Column('underkategori', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('muskel_id'),
    sa.UniqueConstraint('muskel_navn')
    )
    op.create_index(op.f('ix_muskler_muskel_id'), 'muskler', ['muskel_id'], unique=False)
    op.create_table('ovelser',
    sa.Column('ovelse_id', sa.Integer(), nullable=False),
    sa.Column('ovelse_navn', sa.String(length=200), nullable=False),
    sa.Column('force', sa.String(length=20), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('mechanic', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('gif_url', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('bilde_1_url', sa.Text(), nullable=True),
    sa.Column('bilde_2_url', sa.Text(), nullable=True),
    sa.Column('instruksjoner', sa.Text(), nullable=True),
    sa.Column('tips', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('vanlige_feil', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('kilde_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ovelse_id'),
    sa.UniqueConstraint('ovelse_navn')
    )
    op.create_index(op.f('ix_ovelser_ovelse_id'), 'ovelser', ['ovelse_id'], unique=False)
    op.create_table('utstyr',
    sa.Column('utstyr_id', sa.Integer(), nullable=False),
    sa.Column('utstyr_navn', sa.String(length=100), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('utstyr_id'),
    sa.UniqueConstraint('utstyr_navn')
    )
    op.create_index(op.f('ix_utstyr_utstyr_id'), 'utstyr', ['utstyr_id'], unique=False)
    op.create_table('antagonistiske_par',
    sa.Column('par_id', sa.Integer(), nullable=False),
    sa.Column('muskel_1_id', sa.Integer(), nullable=False),
    sa.Column('muskel_2_id', sa.Integer(), nullable=False),
    sa.Column('onsket_ratio', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['muskel_1_id'], ['muskler.muskel_id'], ),
    sa.ForeignKeyConstraint(['muskel_2_id'], ['muskler.muskel_id'], ),
    sa.PrimaryKeyConstraint('par_id')
    )
    op.create_index(op.f('ix_antagonistiske_par_par_id'), 'antagonistiske_par', ['par_id'], unique=False)
    op.create_table('bruker_muskel_status',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('bruker_id', sa.Integer(), nullable=False),
    sa.Column('muskel_id', sa.Integer(), nullable=False),
    sa.Column('sist_trent_dato', sa.TIMESTAMP(), nullable=True),
    sa.Column('antall_ganger_trent', sa.Integer(), nullable=True),
    sa.Column('total_volum', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['bruker_id'], ['brukere.bruker_id'], ),
    sa.ForeignKeyConstraint(['muskel_id'], ['muskler.muskel_id'], ),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('bruker_id', 'muskel_id', name='uq_bruker_muskel')
    )
    op.create_index(op.f('ix_bruker_muskel_status_status_id'), 'bruker_muskel_status', ['status_id'], unique=False)
    op.create_table('bruker_ovelse_historikk',
    sa.Column('historikk_id', sa.Integer(), nullable=False),
    sa.Column('bruker_id', sa.Integer(), nullable=False),
    sa.Column('ovelse_id', sa.Integer(), nullable=False),
    sa.Column('sist_brukt_dato', sa.TIMESTAMP(), nullable=True),
    sa.Column('antall_ganger_brukt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bruker_id'], ['brukere.bruker_id'], ),
    sa.ForeignKeyConstraint(['ovelse_id'], ['ovelser.ovelse_id'], ),
    sa.PrimaryKeyConstraint('historikk_id'),
    sa.UniqueConstraint('bruker_id', 'ovelse_id', name='uq_bruker_ovelse')
    )
    op.create_index(op.f('ix_bruker_ovelse_historikk_historikk_id'), 'bruker_ovelse_historikk', ['historikk_id'], unique=False)
    op.create_table('bruker_utstyr_profiler',
    sa.Column('profil_id', sa.Integer(), nullable=False),
    sa.Column('bruker_id', sa.Integer(), nullable=False),
    sa.Column('profil_navn', sa.String(length=50), nullable=False),
    sa.Column('utstyr_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bruker_id'], ['brukere.bruker_id'], ),
    sa.PrimaryKeyConstraint('profil_id'),
    sa.UniqueConstraint('bruker_id', 'profil_navn', name='uq_bruker_profil')
    )
    op.create_index(op.f('ix_bruker_utstyr_profiler_profil_id'), 'bruker_utstyr_profiler', ['profil_id'], unique=False)
    op.create_table('invitasjoner',
    sa.Column('invitasjon_id', sa.Integer(), nullable=False),
    sa.Column('invitasjonskode', sa.String(length=50), nullable=False),
    sa.Column('opprettet_av_bruker_id', sa.Integer(), nullable=True),
    sa.Column('epost', sa.String(length=255), nullable=True),
    sa.Column('brukt', sa.Boolean(), nullable=True),
    sa.Column('opprettet_dato', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('utloper_dato', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['opprettet_av_bruker_id'], ['brukere.bruker_id'], ),
    sa.PrimaryKeyConstraint('invitasjon_id')
    )
    op.create_index(op.f('ix_invitasjoner_invitasjon_id'), 'invitasjoner', ['invitasjon_id'], unique=False)
    op.create_index(op.f('ix_invitasjoner_invitasjonskode'), 'invitasjoner', ['invitasjonskode'], unique=True)
    op.create_table('ovelse_muskler',
    sa.Column('ovelse_id', sa.Integer(), nullable=False),
    sa.Column('muskel_id', sa.Integer(), nullable=False),
    sa.Column('muskel_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['muskel_id'], ['muskler.muskel_id'], ),
    sa.ForeignKeyConstraint(['ovelse_id'], ['ovelser.ovelse_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ovelse_id', 'muskel_id')
    )
    op.create_table('ovelse_utstyr',
    sa.Column('ovelse_id', sa.Integer(), nullable=False),
    sa.Column('utstyr_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ovelse_id'], ['ovelser.ovelse_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utstyr_id'], ['utstyr.utstyr_id'], ),
    sa.PrimaryKeyConstraint('ovelse_id', 'utstyr_id')
    )
    op.create_table('ovelser_utfort',
    sa.Column('utfort_id', sa.Integer(), nullable=False),
    sa.Column('bruker_id', sa.Integer(), nullable=False),
    sa.Column('ovelse_id', sa.Integer(), nullable=False),
    sa.Column('sett', sa.Integer(), nullable=False),
    sa.Column('repetisjoner', sa.Integer(), nullable=False),
    sa.Column('vekt', sa.DECIMAL(), nullable=False),
    sa.Column('tidspunkt', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bruker_id'], ['brukere.bruker_id'], ),
    sa.ForeignKeyConstraint(['ovelse_id'], ['ovelser.ovelse_id'], ),
    sa.PrimaryKeyConstraint('utfort_id')
    )
    op.create_index(op.f('ix_ovelser_utfort_tidspunkt'), 'ovelser_utfort', ['tidspunkt'], unique=False)
    op.create_index(op.f('ix_ovelser_utfort_utfort_id'), 'ovelser_utfort', ['utfort_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ovelser_utfort_utfort_id'), table_name='ovelser_utfort')
    op.drop_index(op.f('ix_ovelser_utfort_tidspunkt'), table_name='ovelser_utfort')
    op.drop_table('ovelser_utfort')
    op.drop_table('ovelse_utstyr')
    op.drop_table('ovelse_muskler')
    op.drop_index(op.f('ix_invitasjoner_invitasjonskode'), table_name='invitasjoner')
    op.drop_index(op.f('ix_invitasjoner_invitasjon_id'), table_name='invitasjoner')
    op.drop_table('invitasjoner')
    op.drop_index(op.f('ix_bruker_utstyr_profiler_profil_id'), table_name='bruker_utstyr_profiler')
    op.drop_table('bruker_utstyr_profiler')
    op.drop_index(op.f('ix_bruker_ovelse_historikk_historikk_id'), table_name='bruker_ovelse_historikk')
    op.drop_table('bruker_ovelse_historikk')
    op.drop_index(op.f('ix_bruker_muskel_status_status_id'), table_name='bruker_muskel_status')
    op.drop_table('bruker_muskel_status')
    op.drop_index(op.f('ix_antagonistiske_par_par_id'), table_name='antagonistiske_par')
    op.drop_table('antagonistiske_par')
    op.drop_index(op.f('ix_utstyr_utstyr_id'), table_name='utstyr')
    op.drop_table('utstyr')
    op.drop_index(op.f('ix_ovelser_ovelse_id'), table_name='ovelser')
    op.drop_table('ovelser')
    op.drop_index(op.f('ix_muskler_muskel_id'), table_name='muskler')
    op.drop_table('muskler')
    op.drop_index(op.f('ix_brukere_epost'), table_name='brukere')
    op.drop_index(op.f('ix_brukere_brukernavn'), table_name='brukere')
    op.drop_index(op.f('ix_brukere_bruker_id'), table_name='brukere')
    op.drop_table('brukere')
    # ### end Alembic commands ###
